#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# Disable Less history.
export LESSHISTFILE=/dev/null

# Install NPM packages locally.
export npm_config_prefix=~/.npm/node_modules

export PYTHONSTARTUP=~/.pythonrc  # Python startup file.
export BUNDLE_PATH=~/.bundle      # Install bundle gems locally.
