#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

export LESSHISTFILE=/dev/null     # Disable Less history.
export PYTHONSTARTUP=~/.pythonrc  # Python startup file.

# Better scrolling on Firefox.
export MOZ_USE_XINPUT2=1
